# Generated by Django 3.2.9 on 2022-02-12 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='avatar/', verbose_name='Аватар')),
                ('number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Номер телефона')),
                ('mail', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Эл.почта')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Задача')),
                ('slug', models.SlugField(blank=True, max_length=30, verbose_name='Слаг')),
                ('photo', models.ImageField(blank=True, upload_to='photo/%Y/%m/', verbose_name='Фото')),
                ('file', models.FileField(blank=True, upload_to='file/%Y/%m/', verbose_name='Файл')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
                ('data_deadline', models.DateTimeField(blank=True, null=True, verbose_name='Срок исполнения')),
                ('is_public', models.BooleanField(default=True)),
                ('is_ok', models.BooleanField(default=False)),
                ('is_negative', models.BooleanField(default=False)),
                ('is_scan', models.BooleanField(default=False)),
                ('is_from', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='is_from_user', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал задачу?')),
                ('is_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='is_to_user', to=settings.AUTH_USER_MODEL, verbose_name='Для кого задача?')),
            ],
            options={
                'verbose_name': 'Список задач',
                'verbose_name_plural': 'Списки задач',
                'ordering': ['-date_create'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todofamily.todo', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_is_from', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['date'],
            },
        ),
    ]
