# Generated by Django 3.2.9 on 2021-12-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_from', models.CharField(max_length=50)),
                ('is_to', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('photo', models.ImageField(null=True, upload_to='photo/%Y/%m/')),
                ('file', models.FileField(null=True, upload_to='file/%Y/%m/')),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('data_update', models.DateTimeField(auto_now=True)),
                ('data_deadline', models.DateTimeField(null=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
        ),
    ]
