# Generated by Django 3.2.9 on 2021-12-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todofamily', '0003_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-date_create'], 'verbose_name': 'Список задач', 'verbose_name_plural': 'Спиок задач'},
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_from',
            field=models.CharField(max_length=50, verbose_name='Кто?'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_to',
            field=models.CharField(max_length=50, verbose_name='Кому?'),
        ),
    ]
