# Generated by Django 3.2.9 on 2021-12-24 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todofamily', '0006_auto_20211211_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_is_from', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='content',
            field=models.TextField(verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='data_deadline',
            field=models.DateTimeField(blank=True, verbose_name='Срок исполнения'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='file',
            field=models.FileField(blank=True, upload_to='file/%Y/%m/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='is_from_user', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал задачу?'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='is_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='is_to_user', to=settings.AUTH_USER_MODEL, verbose_name='Для кого задача?'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='avatar/', verbose_name='Аватар')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
