# Generated by Django 3.2.9 on 2021-12-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todofamily', '0007_auto_20211224_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='data_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Срок исполнения'),
        ),
    ]
