# Generated by Django 3.2.9 on 2021-12-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todofamily', '0008_alter_todo_data_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='Комментарий'),
        ),
    ]
