# Generated by Django 3.2.9 on 2021-12-24 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todofamily', '0009_alter_comment_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='date',
        ),
    ]
