# Generated by Django 3.2.9 on 2022-01-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todofamily', '0011_auto_20211224_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='mail',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Эл.почта'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='number',
            field=models.IntegerField(blank=True, default=1, unique=True, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
    ]
