# Generated by Django 3.2.9 on 2022-01-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todofamily', '0012_auto_20220102_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Номер телефона'),
        ),
    ]
