# Generated by Django 3.2.9 on 2022-01-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todofamily', '0013_alter_userinfo_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='is_negative',
            field=models.BooleanField(default=False),
        ),
    ]
